* Makefile.am, Makefile.in: Check that system.garlic.debug is 	the first garlic elaborated package.
	* s-garexc.adb: Add visibility on system.garlic.debug.

	* s-parint.adb: Move Delete_Termination_Sanity_File to the very
	last shutdown step.

	* s-ganobl.adb (C_Accept): When Thin.C_Accept fails and Errno is
	Eagain, try again later.

	* s-garfil.adb, s-garfil.ads, s-gafizi.adb, s-gafizi.ads,
 	s-garhea.adb: Remove a copy of stream element array.

Subversion-branch: /importfromcvs/trunk
Subversion-revision: 47150

diff --git a/Garlic/Makefile.in b/Garlic/Makefile.in
--- a/Garlic/Makefile.in
+++ b/Garlic/Makefile.in
@@ -10,6 +10,8 @@
 # even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 # PARTICULAR PURPOSE.
 
+#
+
 
 SHELL = /bin/sh
 
@@ -458,6 +460,13 @@ inlining: all-local
 linktest: ${srcdir}/linktest.adb ${OBJECTS}
 	${GNATMAKE} -c -a -m -I${srcdir} -I. ${srcdir}/linktest.adb
 	${GNATBIND} ${srcdir}/linktest.ali -I. -I${srcdir}
+	@${GNATBIND} -l ${srcdir}/linktest.ali -I. -I${srcdir} \
+	   | grep 'system.garlic.*body' | sed -n '1,1p' \
+	   | ${SED} 's/^.*garlic.\(.*\) .*$$/\1/g' > first;
+	@if test `cat first` != "debug"; then\
+	   echo "system.garlic.debug should be elaborted first";\
+	   exit 1;\
+	fi
 
 install-extra-libs: ${FILTERINSTALL} inlining
 
