Merge with 3.11b branch
Subversion-branch: /importfromcvs/trunk
Subversion-revision: 47071

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,8 +24,8 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-protocols=list   Enumerate protocol list"
 ac_help="$ac_help
-  --enable-thread-blocking-io
-                          Turn on thread blocking io mode (default=test)"
+  --with-thread-blocking-io
+                          Pretend that system has thread blocking I/Os"
 ac_help="$ac_help
   --with-filters=list     Enumerate filter list (default=none+zip)"
 ac_help="$ac_help
@@ -1667,7 +1667,7 @@ esac
 
 echo "$ac_t""$PSNAME" 1>&6
 echo $ac_n "checking preserve the original file properties with""... $ac_c" 1>&6
-echo "configure:1670: checking preserve the original file properties with" >&5
+echo "configure:1671: checking preserve the original file properties with" >&5
 case "${PLATFORM_SPECIFIC}" in
    w) CP_PRESERVE="-lf";;
    *) CP_PRESERVE="-p";;
@@ -1679,7 +1679,7 @@ echo "$ac_t""$CP_PRESERVE" 1>&6
 # LinuxThreads with libc1. This crashes the machine.
 #
 echo $ac_n "checking if platform supports local launching""... $ac_c" 1>&6
-echo "configure:1682: checking if platform supports local launching" >&5
+echo "configure:1683: checking if platform supports local launching" >&5
 case "${target}" in
   *-linux*libc1*)	SUPPORTS_LOCAL_LAUNCH=False; echo "$ac_t""no" 1>&6;;
   *)            	SUPPORTS_LOCAL_LAUNCH=True; echo "$ac_t""yes" 1>&6;;
@@ -1689,7 +1689,7 @@ esac
 # Remote shell
 #
 echo $ac_n "checking which remote shell to use""... $ac_c" 1>&6
-echo "configure:1692: checking which remote shell to use" >&5
+echo "configure:1693: checking which remote shell to use" >&5
 # Check whether --with-remsh or --without-remsh was given.
 if test "${with_remsh+set}" = set; then
   withval="$with_remsh"
@@ -1704,14 +1704,6 @@ fi
 
 echo "$ac_t""$RSH" 1>&6
 #
-# Checking whether s-gtplsp.adb exists for this platform
-#
-case ${PLATFORM_SPECIFIC} in
-  w) TCP_PLATFORM_SOURCE=s-gtplsp.adb;;
-  *) TCP_PLATFORM_SOURCE=s-gtplsp.ads;;
-esac
-
-#
 # Protocol list
 #
 # Check whether --with-protocols or --without-protocols was given.
@@ -1719,7 +1711,7 @@ if test "${with_protocols+set}" = set; then
   withval="$with_protocols"
   
   echo $ac_n "checking default protocols""... $ac_c" 1>&6
-echo "configure:1722: checking default protocols" >&5
+echo "configure:1715: checking default protocols" >&5
   LIST="";
   PROTOCOLSSOURCES="";
   PROTOCOLSOBJECTS="";
@@ -1744,7 +1736,7 @@ echo "configure:1722: checking default protocols" >&5
 else
   
 echo $ac_n "checking default protocols""... $ac_c" 1>&6
-echo "configure:1747: checking default protocols" >&5
+echo "configure:1740: checking default protocols" >&5
 PROTOCOLSSOURCES="\$(TCPSOURCES)";
 PROTOCOLSOBJECTS="\$(TCPOBJECTS)";
 TCP_INCLUDED=""
@@ -1752,58 +1744,48 @@ echo "$ac_t""tcp" 1>&6
 
 fi
 
-if test "$TCP_INCLUDED" = ""; then
+if test -z "$TCP_INCLUDED"; then
   if test -f $srcdir/Garlic/5${PLATFORM_SPECIFIC}gtplsp.ads; then
-    cp $srcdir/Garlic/5${PLATFORM_SPECIFIC}gtplsp.ads \
-       $srcdir/Garlic/s-gtplsp.ads
+    S_GTPLSP_ADS="5${PLATFORM_SPECIFIC}gtplsp.ads";
   else
-    cp $srcdir/Garlic/5egtplsp.ads $srcdir/Garlic/s-gtplsp.ads
-  fi;
+    S_GTPLSP_ADS="5egtplsp.ads"
+  fi
   if test -f $srcdir/Garlic/5${PLATFORM_SPECIFIC}gtplsp.adb; then
-    cp $srcdir/Garlic/5${PLATFORM_SPECIFIC}gtplsp.adb \
-       $srcdir/Garlic/s-gtplsp.adb
+    S_GTPLSP_ADB="5${PLATFORM_SPECIFIC}gtplsp.adb"
+    TCP_PLATFORM_SOURCE="s-gtplsp.adb"
+  else
+    S_GTPLSP_ADB=""
+    TCP_PLATFORM_SOURCE="s-gtplsp.ads"
   fi;
-  # Check whether --enable-thread-blocking-io or --disable-thread-blocking-io was given.
-if test "${enable_thread_blocking_io+set}" = set; then
-  enableval="$enable_thread_blocking_io"
   
-   echo "with System.Garlic.Non_Blocking;"         >$srcdir/Garlic/s-gatcop.ads
-   echo "package System.Garlic.TCP.Operations"    >>$srcdir/Garlic/s-gatcop.ads
-   echo "   renames System.Garlic.Non_Blocking;"  >>$srcdir/Garlic/s-gatcop.ads
-   PROTOCOLSSOURCES="${PROTOCOLSSOURCES} \$(NOBLTCPSOURCES)"
-   PROTOCOLSOBJECTS="${PROTOCOLSOBJECTS} \$(NOBLTCPOBJECTS)"
+  
+  
+  # Check whether --with-thread-blocking-io or --without-thread-blocking-io was given.
+if test "${with_thread_blocking_io+set}" = set; then
+  withval="$with_thread_blocking_io"
+  
+   if test "$withval" = "yes"; then
+     ISTHRBIO="yes"
+   elif test "$withval" = "no"; then
+     ISTHRBIO="no"
+   else
+     { echo "configure: error: unknown value ${withval}" 1>&2; exit 1; }
+   fi
   
 else
   
-    ISTHRBIO="yes"
     if test "${PLATFORM_SPECIFIC}" = "w"; then
-      echo $ac_n "checking for thread-blocking I/O""... $ac_c" 1>&6
-echo "configure:1781: checking for thread-blocking I/O" >&5
-      echo "with System.Garlic.Thin;"              >$srcdir/Garlic/s-gatcop.ads
-      echo "package System.Garlic.TCP.Operations" >>$srcdir/Garlic/s-gatcop.ads
-      echo "   renames System.Garlic.Thin;"       >>$srcdir/Garlic/s-gatcop.ads
-   else
-      echo $ac_n "checking for thread-blocking I/O (long)""... $ac_c" 1>&6
-echo "configure:1787: checking for thread-blocking I/O (long)" >&5
-      ${ADA} -c -gnatg $srcdir/Garlic/${TCP_PLATFORM_SOURCE} -I$srcdir/Garlic;
-      ${ADA} -c -gnatg $srcdir/Garlic/s-garlic.ads -I$srcdir/Garlic;
-      ${ADA} -c -gnatg $srcdir/Garlic/s-garthi.ads -I$srcdir/Garlic;
-      ${GNATMAKE} -q -m isthrbio.adb -I$srcdir/Garlic -bargs -t;
-      if ./isthrbio${EXEEXT} Garlic/s-gatcop.ads; then
-        ISTHRBIO="no"
-      fi
-    fi
-    if test "${ISTHRBIO}" = "no"; then
-	echo "$ac_t""no" 1>&6
-	PROTOCOLSSOURCES="${PROTOCOLSSOURCES} \$(NOBLTCPSOURCES)"
-	PROTOCOLSOBJECTS="${PROTOCOLSOBJECTS} \$(NOBLTCPOBJECTS)"
+      ISTHRBIO="yes"
     else
-	echo "$ac_t""yes" 1>&6
+      ISTHRBIO="test"
     fi
   
 fi
 
+ PROTOCOLSSOURCES="${PROTOCOLSSOURCES} \$(NOBLTCPSOURCES)"
+ PROTOCOLSOBJECTS="${PROTOCOLSOBJECTS} \$(NOBLTCPOBJECTS)"
 fi
+
 
 
 
@@ -1823,7 +1805,7 @@ else
 fi
 
 echo $ac_n "checking default filters""... $ac_c" 1>&6
-echo "configure:1826: checking default filters" >&5
+echo "configure:1809: checking default filters" >&5
 
 if test -d Garlic; then
   :
@@ -1858,7 +1840,7 @@ fi
 #
 if test $target = $host; then
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:1861: checking how to run the C preprocessor" >&5
+echo "configure:1844: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -1873,13 +1855,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 1876 "configure"
+#line 1859 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1882: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1865: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -1890,13 +1872,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 1893 "configure"
+#line 1876 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1899: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1882: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -1922,17 +1904,17 @@ for ac_hdr in stdio.h sys/types.h sys/socket.h errno.h netdb.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1925: checking for $ac_hdr" >&5
+echo "configure:1908: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1930 "configure"
+#line 1913 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1935: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1918: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1962,17 +1944,17 @@ for ac_hdr in netinet/in.h signal.h fcntl.h termio.h termios.h sys/file.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1965: checking for $ac_hdr" >&5
+echo "configure:1948: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1970 "configure"
+#line 1953 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1975: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1958: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2002,17 +1984,17 @@ for ac_hdr in sys/ioctl.h netinet/tcp.h sys/systeminfo.h poll.h stropts.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2005: checking for $ac_hdr" >&5
+echo "configure:1988: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2010 "configure"
+#line 1993 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2015: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1998: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2042,17 +2024,17 @@ for ac_hdr in sys/conf.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2045: checking for $ac_hdr" >&5
+echo "configure:2028: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2050 "configure"
+#line 2033 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2055: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2038: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2276,10 +2258,13 @@ s%@PSNAME@%$PSNAME%g
 s%@CP_PRESERVE@%$CP_PRESERVE%g
 s%@SUPPORTS_LOCAL_LAUNCH@%$SUPPORTS_LOCAL_LAUNCH%g
 s%@RSH@%$RSH%g
+s%@S_GTPLSP_ADS@%$S_GTPLSP_ADS%g
+s%@S_GTPLSP_ADB@%$S_GTPLSP_ADB%g
 s%@TCP_PLATFORM_SOURCE@%$TCP_PLATFORM_SOURCE%g
 s%@PROTOCOLSSOURCES@%$PROTOCOLSSOURCES%g
 s%@PROTOCOLSOBJECTS@%$PROTOCOLSOBJECTS%g
 s%@TCP_INCLUDED@%$TCP_INCLUDED%g
+s%@ISTHRBIO@%$ISTHRBIO%g
 /@FILTERFILE@/r $FILTERFILE
 s%@FILTERFILE@%%g
 s%@EXTRA_LIBS@%$EXTRA_LIBS%g
