New version of cobuild: more clever, and more easily adaptable to other projects.
[Imported from Perforce change 3018 at 2006-12-01 19:17:08]

Subversion-branch: /trunk/adabroker
Subversion-revision: 32767

diff --git a/broca/utils/cobuild b/broca/utils/cobuild
--- a/broca/utils/cobuild
+++ b/broca/utils/cobuild
@@ -1,8 +1,10 @@
 #! /bin/sh
 
-# cobuild: Build AdaBroker from a checked-out wavefront.
+# cobuild: Build something from a checked-out wavefront.
 
-# $Id: //depot/adabroker/main/broca/utils/cobuild#6 $
+# $Id: //depot/adabroker/main/broca/utils/cobuild#7 $
+
+PROJECT=AdaBroker
 
 usage () {
   echo "Usage: $0 -m EMAIL_ADDRESS -C CLIENT_WORKSPACE_TOP -o OUTPUT_DIR [ -c CHANGELIST ]"
@@ -18,7 +20,7 @@ do
       CLIENT_TOP=$OPTARG
       ;;
     c)
-      CHANGELIST="@$OPTARG"
+      CHANGELIST="$OPTARG"
       ;;
     o)
       OUTDIR=$OPTARG
@@ -52,18 +54,39 @@ export P4CONFIG MAILTO OUTDIR CLIENT_TOP TMPDIR
 set -e
 umask 022
 
-# Kill any previous build.
-
 PIDFILE=$OUTDIR/build.pid
+CHGFILE=$OUTDIR/build.change
 LOGFILE=$OUTDIR/build.log
+
+# Take mutex
 
 lockfile $PIDFILE.lock
 trap 'rm -f $PIDFILE.lock' 0
 
+# Determine change level to be built.
+
+if [ "x$CHANGELIST" = x ]
+then
+  CHANGELIST=`p4 changes -m 1 ... | awk '{print \$2}'`
+fi
+
+# Kill any previous build.
+
 if [ -f $PIDFILE ]
 then
   OLDPID=`cat $PIDFILE`
-  kill $OLDPID > /dev/null 2>&1 || true
+  if [ "x$OLDPID" != x ] && ps -p $OLDPID > /dev/null
+  then
+    # Build in progress.
+
+    [ -f "$CHGFILE" ] && OLDCHG=`cat "$CHGFILE`"
+    if [ "$OLDCHG" -ge "$CHANGELIST" ]
+    then
+      # Already building this changelist or a more recent one.
+      exit 0
+    fi
+    kill $OLDPID > /dev/null 2>&1 || true
+  fi
 fi
 
 # Here comes the hot builder.
@@ -72,12 +95,13 @@ exec > $LOGFILE 2>&1
 
 # Prepare execution.
 
-echo "---------- Build started: `date`"
+echo "---------- Starting build of ${PROJECT} ch. ${CHANGELIST}: `date`"
+echo "---------- Syncing"
 
 cd $CLIENT_TOP
 #p4 sync "#none"
 #rm -fr $CLIENT_TOP/*
-p4 sync $CHANGELIST
+p4 sync @$CHANGELIST
 
 CHANGE=`p4 changes -m 1 ...#have | awk '{print \$2}'`
 export CHANGE
@@ -86,8 +110,8 @@ export CHANGE
   set -e
   sleep 10
 
-  echo "---------- Building AdaBroker ch. $CHANGE"
-  ./support/reconfig
+  echo "---------- Building"
+  [ -x ./support/reconfig ] && ./support/reconfig
   cd $OUTDIR
   mkdir build > /dev/null 2>&1 || true
   mkdir install > /dev/null 2>&1 || true
@@ -133,9 +157,9 @@ fi
 
 if $SUCCESS
 then
-  echo -e "$MSG" | Mail -s "AdaBroker build $CHANGE $STATUS" $MAILTO
+  echo -e "$MSG" | Mail -s "${PROJECT} build $CHANGE $STATUS" $MAILTO
 else
-  cat $OUTDIR/build.log | Mail -s "AdaBroker BUILD $CHANGE FAILED" $MAILTO
+  cat $OUTDIR/build.log | Mail -s "${PROJECT} BUILD $CHANGE FAILED" $MAILTO
 fi
 
 lockfile $PIDFILE.lock
